vich_uploader:
    db_driver: orm

    mappings:
        devisDocument:
            uri_prefix: /upload/documents/devis
            upload_destination: '%kernel.project_dir%/public/upload/documents/devis'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        eventImage:
            uri_prefix: upload/images/event
            upload_destination: '%kernel.project_dir%/public/upload/images/event'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        realisationImage:
            uri_prefix: upload/images/realisation
            upload_destination: '%kernel.project_dir%/public/upload/images/realisation'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        teamPhoto:
            uri_prefix: upload/images/team
            upload_destination: '%kernel.project_dir%/public/upload/images/team'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        temoignageImage:
            uri_prefix: upload/images/temoignage
            upload_destination: '%kernel.project_dir%/public/upload/images/temoignage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
